#####Get_Linear_Regression#####
library(grid)
library(ggplot2)
#ggplot(result,aes(x=GM_AC_Return, y=S.P_AC_Return)) + 
#  geom_point(alpha=0.1,size=1.0,shape=21,fill='white',stroke=2,color='red')+
 # geom_smooth(color='darkgrey',method='lm')
result=art_data_drop
l=geom_smooth(color='blue',method='lm')
alpha=0.3
pit1=geom_point(alpha=alpha,size=1.0,shape=21,fill='white',stroke=2,color='red')
pit2=geom_point(alpha=alpha,size=1.0,shape=21,fill='white',stroke=2,color='orange')
pit3=geom_point(alpha=alpha,size=1.0,shape=21,fill='white',stroke=2,color='yellow')
pit4=geom_point(alpha=alpha,size=1.0,shape=21,fill='white',stroke=2,color='darkgreen')
pit5=geom_point(alpha=alpha,size=1.0,shape=21,fill='white',stroke=2,color='lightgreen')
pit6=geom_point(alpha=alpha,size=1.0,shape=21,fill='white',stroke=2,color='lightblue')
pit7=geom_point(alpha=alpha,size=1.0,shape=21,fill='white',stroke=2,color='purple')
pit8=geom_point(alpha=alpha,size=1.0,shape=21,fill='white',stroke=2,color='black')
pit9=geom_point(alpha=alpha,size=1.0,shape=21,fill='white',stroke=2,color='darkgrey')
pit10=geom_point(alpha=alpha,size=1.0,shape=21,fill='white',stroke=2,color='brown')
pit11=geom_point(alpha=alpha,size=1.0,shape=21,fill='white',stroke=2,color='pink')
g1=ggplot(result,aes(x=danceability,y=popularity))
g2=ggplot(result,aes(x=energy,y=popularity))
g3=ggplot(result,aes(x=valence,y=popularity))
g4=ggplot(result,aes(x=tempo,y=popularity))
g5=ggplot(result,aes(x=loudness,y=popularity))
g6=ggplot(result,aes(x=acousticness,y=popularity))
g7=ggplot(result,aes(x=instrumentalness,y=popularity))
g8=ggplot(result,aes(x=liveness,y=popularity))
g9=ggplot(result,aes(x=speechiness,y=popularity))
g10=ggplot(result,aes(x=duration_ms,y=popularity))
g11=ggplot(result,aes(x=count,y=popularity))
f1=g1+pit1+l
f2=g2+pit2+l
f3=g3+pit3+l
f4=g4+pit4+l
f5=g5+pit5+l
f6=g6+pit6+l
f7=g7+pit7+l
f8=g8+pit8+l
f9=g9+pit9+l
f10=g10+pit10+l
f11=g11+pit11+l
pdf('linear_regression.pdf',width=15,height=15)
grid.newpage()
pushViewport(viewport(layout=grid.layout(4,3)))
vplayout=function(x,y)
  viewport(layout.pos.row=x,layout.pos.col=y)
print(f1,vp=vplayout(1,1))
print(f2,vp=vplayout(1,2))
print(f3,vp=vplayout(1,3))
print(f4,vp=vplayout(2,1))
print(f5,vp=vplayout(2,2))
print(f6,vp=vplayout(2,3))
print(f7,vp=vplayout(3,1))
print(f8,vp=vplayout(3,2))
print(f9,vp=vplayout(3,3))
print(f10,vp=vplayout(4,1))
print(f11,vp=vplayout(4,2))
dev.off()
